version: '3'

services:
 db:
   container_name: pitthayakorn-postgres
   ports:
     - 54322:5432
   environment:
     - POSTGRES_USER=${DB_USER}
     - POSTGRES_PASSWORD=${DB_PASS}
   image: postgres:14.4
   restart: unless-stopped

 pgadmin:
  container_name: pitthayakorn-pgadmin
  image: dpage/pgadmin4:latest
  ports:
    - 4433:443
    - 8080:80
  environment:
    - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
    - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
  restart: unless-stopped

 strapi:
  container_name: pitthayakorn-strapi
  image: naskio/strapi:latest
  ports:
    - 1337:1337
  environment:
    - DATABASE_CLIENT=${DA_CLIENT}
    - DATABASE_HOST=${DA_HOST}
    - DATABASE_PORT=${DA_PORT}
    - DATABASE_NAME=${DA_NAME}
    - DATABASE_USERNAME=${DA_USERNAME}
    - DATABASE_PASSWORD=${DA_PASSWORD}
  restart: unless-stopped
