version: '3'

services:
 db:
   container_name: pitthayakorn-postgres
   ports:
     - 54322:5432
   environment:
     - POSTGRES_USER=pitthayakorn
     - POSTGRES_PASSWORD=54322
   image: postgres:14.4
   restart: unless-stopped

 pgadmin:
  container_name: pitthayakorn-pgadmin
  image: dpage/pgadmin4:latest
  ports:
    - 4433:443
    - 8080:80
  environment:
    - PGADMIN_DEFAULT_EMAIL=pitthayakorn-p@rmutp.ac.th
    - PGADMIN_DEFAULT_PASSWORD=54321
  restart: unless-stopped

 strapi:
  container_name: pitthayakorn-strapi
  image: naskio/strapi:latest
  ports:
    - 1337:1337
  environment:
    - DATABASE_CLIENT=postgres
    - DATABASE_HOST=172.26.29.167
    - DATABASE_PORT=54322
    - DATABASE_NAME=strapi
    - DATABASE_USERNAME=pitthayakorn
    - DATABASE_PASSWORD=54322
  restart: unless-stopped
